# Generated by Django 4.2.7 on 2025-11-16 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('activity_type', models.CharField(choices=[('sightseeing', 'Sightseeing'), ('dining', 'Dining'), ('adventure', 'Adventure'), ('shopping', 'Shopping'), ('relaxation', 'Relaxation'), ('cultural', 'Cultural'), ('beach', 'Beach'), ('hiking', 'Hiking'), ('sports', 'Sports'), ('wellness', 'Wellness')], max_length=20)),
                ('duration_minutes', models.IntegerField()),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('children_friendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.CharField(choices=[('budget', 'Budget ($0 - $1000)'), ('moderate', 'Moderate ($1000 - $3000)'), ('luxury', 'Luxury ($3000+)')], max_length=20)),
                ('trip_type', models.CharField(choices=[('adventure', 'Adventure'), ('relaxation', 'Relaxation'), ('cultural', 'Cultural'), ('romantic', 'Romantic'), ('family', 'Family'), ('business', 'Business'), ('solo', 'Solo Travel')], max_length=20)),
                ('travelers', models.IntegerField(default=1)),
                ('children_count', models.IntegerField(default=0, verbose_name='Number of Children')),
                ('children_friendly', models.BooleanField(default=False, verbose_name='Children Friendly')),
                ('activity_preferences', models.JSONField(blank=True, default=list, help_text='Selected activity preferences')),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField()),
                ('activities', models.JSONField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='planner.itinerary')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
