# Generated by Django 4.2.7 on 2025-11-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='dayplan',
            options={'ordering': ['day_number'], 'verbose_name': 'Day Plan', 'verbose_name_plural': 'Day Plans'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Itinerary', 'verbose_name_plural': 'Itineraries'},
        ),
    ]
