# Generated by Django 4.2.7 on 2025-11-17 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_otpverification_alter_activity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['name'], 'verbose_name': '🎯 Activity', 'verbose_name_plural': '🎯 Activities'},
        ),
        migrations.AlterModelOptions(
            name='dayplan',
            options={'ordering': ['day_number'], 'verbose_name': '📋 Day Plan', 'verbose_name_plural': '📋 Day Plans'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['name'], 'verbose_name': '📍 Destination', 'verbose_name_plural': '📍 Destinations'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'ordering': ['-created_at'], 'verbose_name': '📅 Itinerary', 'verbose_name_plural': '📅 Itineraries'},
        ),
        migrations.AlterModelOptions(
            name='otpverification',
            options={'verbose_name': '🔐 OTP Verification', 'verbose_name_plural': '🔐 OTP Verifications'},
        ),
        migrations.AddField(
            model_name='activity',
            name='booking_url',
            field=models.URLField(blank=True, verbose_name='🔗 Booking URL'),
        ),
        migrations.AddField(
            model_name='activity',
            name='difficulty_level',
            field=models.CharField(choices=[('easy', '🟢 Easy'), ('moderate', '🟡 Moderate'), ('difficult', '🔴 Difficult')], default='easy', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='🖼️ Activity Image'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='notes',
            field=models.TextField(blank=True, verbose_name='📝 Day Notes'),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='weather_forecast',
            field=models.JSONField(blank=True, null=True, verbose_name='🌤️ Weather Forecast'),
        ),
        migrations.AddField(
            model_name='destination',
            name='best_season',
            field=models.CharField(blank=True, max_length=100, verbose_name='🌞 Best Season to Visit'),
        ),
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, verbose_name='🖼️ Destination Image'),
        ),
        migrations.AddField(
            model_name='destination',
            name='popularity_score',
            field=models.IntegerField(default=0, verbose_name='⭐ Popularity Score'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='featured_image',
            field=models.URLField(blank=True, verbose_name='🖼️ Featured Image'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='🌐 Public Itinerary'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('sightseeing', '📸 Sightseeing'), ('dining', '🍽️ Dining'), ('adventure', '🧗 Adventure'), ('shopping', '🛍️ Shopping'), ('relaxation', '🧘 Relaxation'), ('cultural', '🏛️ Cultural'), ('beach', '🏖️ Beach'), ('hiking', '🥾 Hiking'), ('sports', '⚽ Sports'), ('wellness', '💆 Wellness'), ('transport', '🚗 Transport'), ('accommodation', '🏨 Accommodation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='budget',
            field=models.CharField(choices=[('budget', '💰 Budget ($0 - $1000)'), ('moderate', '💸 Moderate ($1000 - $3000)'), ('luxury', '💎 Luxury ($3000+)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='children_count',
            field=models.IntegerField(default=0, verbose_name='👶 Number of Children'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='children_friendly',
            field=models.BooleanField(default=False, verbose_name='👶 Children Friendly'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='trip_type',
            field=models.CharField(choices=[('adventure', '🏔️ Adventure'), ('relaxation', '🏖️ Relaxation'), ('cultural', '🏛️ Cultural'), ('romantic', '💖 Romantic'), ('family', '👨\u200d👩\u200d👧\u200d👦 Family'), ('business', '💼 Business'), ('solo', '🧳 Solo Travel')], max_length=20),
        ),
        migrations.CreateModel(
            name='TravelTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('packing', '🎒 Packing'), ('budget', '💰 Budget'), ('safety', '🛡️ Safety'), ('transport', '🚗 Transport'), ('food', '🍽️ Food'), ('culture', '🎎 Culture'), ('technology', '📱 Technology')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planner.destination')),
            ],
            options={
                'verbose_name': '💡 Travel Tip',
                'verbose_name_plural': '💡 Travel Tips',
                'ordering': ['-created_at'],
            },
        ),
    ]
